services:
  db:
    image: fafnir-postgres-db
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build:
      context: ..
      dockerfile: services/auth-service/Dockerfile
    volumes:
        - ../services/auth-service:/app/services/auth-service
        - ../shared:/app/shared
    ports:
      - "8081:8081"

  user-service:
    build:
      context: ..
      dockerfile: services/user-service/Dockerfile
    volumes:
      - ../services/user-service:/app/services/user-service
      - ../shared:/app/shared
    ports:
      - "8082:8082"

  web-app:
    build:
      context: ../web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../web:/app

volumes:
  pgdata: